---
all:
  children:
    routers:
      hosts:
        HQ1:
          ansible_host: 192.168.0.2
          ansible_user: IT
        HQ2:
          ansible_host: 192.168.0.3
          ansible_user: IT
        SITE1:
          ansible_host: 192.168.1.1
          ansible_user: IT
        SITE2:
          ansible_host: 192.168.2.2
          ansible_user: IT

    switches:
      hosts:
        L3:
          ansible_host: 192.168.3.1
          ansible_user: IT
        ACC1:
          ansible_host: 192.168.0.4
          ansible_user: IT
        ACC2:
          ansible_host: 192.168.0.5
          ansible_user: IT
        DIS1:
          ansible_host: 192.168.0.6
          ansible_user: IT
        DIS2:
          ansible_host: 192.168.0.7
          ansible_user: IT
        SW1:
          ansible_host: 192.168.1.2
          ansible_user: IT
        SW2:
          ansible_host: 192.168.2.2
          ansible_user: IT

  vars:
    ansible_python_interpreter: /usr/bin/python3
